### ISSUE TITLE
About learning with data I have on hand

### ISSUE THREAD

**Issue by myngsk** [hongzhonglu/DeepEnzyme#4]
Hello,  I would like to perform training using the pdb, sequence, and smiles. Is it possible to execute this, including feature extraction?

**Comment by dadadawt** [comment]
Hi，yes，you can do  these operations.

**Comment by myngsk** [comment]
Thanks for the reply!
For the training, I think we need to create files such as atom_dict_0612.pickle, fingerprint_0612.npy, etc. from PDB, sequence, smiles. Is there a published program to create these files?

**Comment by dadadawt** [comment]
yep, in 'Code/Example/example.py', you can find the functions about creating files such as atom_dict_0612.pickle, fingerprint_0612.npy.

**Comment by myngsk** [comment]
Thank you.
If I want to predict for other data, do I need to change sequence, smiles, structure in example.py? Do I need to change other atom_dict, bond_dict, edge_dict, fingerprint_dict, word_dict?

When training with my own data, do I need to change the data specified in fingerprint, smileadjacencies, sequences, proteinadjacencies, kcat_tensor, fingerprint_dict, and word_dict in train.py? Do I need to create any of these data for my data?

I checked example.py and didn't see any process to create fingerprint_dict, for example.
I'm terribly sorry, but I would appreciate it if you could tell me how to train and predict.

**Comment by myngsk** [comment]
Sorry, this matter has resolved itself.
I was able to create the data by looking at example.py and the actual data.
Thank you very much.
